"""tasks payment_charge_id

Revision ID: 528360b0c501
Revises: 3bb9ff5060a1
Create Date: 2026-09-27 02:47:44.648072

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "528360b0c501"
down_revision: str | None = "3bb9ff5060a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("payment_charge_id", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "payment_charge_id")
    # ### end Alembic commands ###
