"""initial schema

Revision ID: b20beb29a1a1
Revises:
Create Date: 2026-09-27 01:54:09.493726

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b20beb29a1a1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_views",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("reward_type", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ad_views_created_at"), "ad_views", ["created_at"], unique=False)
    op.create_index(op.f("ix_ad_views_user_id"), "ad_views", ["user_id"], unique=False)
    op.create_table(
        "battle_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("clan_id", sa.Integer(), nullable=False),
        sa.Column("sector_h3", sa.String(length=16), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("power", sa.BigInteger(), nullable=False),
        sa.Column("flipped", sa.Boolean(), nullable=False),
        sa.Column("prev_owner_clan_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_battle_log_created_at"), "battle_log", ["created_at"], unique=False)
    op.create_index(
        "ix_battle_log_prev_owner", "battle_log", ["prev_owner_clan_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_battle_log_user_id"), "battle_log", ["user_id"], unique=False)
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=False),
        sa.Column("name_ru", sa.String(length=200), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("is_capital", sa.Boolean(), nullable=False),
        sa.Column("sectors_count", sa.Integer(), nullable=False),
        sa.Column("controller_clan_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cities_controller_clan_id"), "cities", ["controller_clan_id"], unique=False
    )
    op.create_index(op.f("ix_cities_country_code"), "cities", ["country_code"], unique=False)
    op.create_index("ix_cities_lat_lng", "cities", ["lat", "lng"], unique=False)
    op.create_index(
        "ix_cities_name_en_prefix",
        "cities",
        [sa.literal_column("lower(name_en)").label("name_en_lower")],
        unique=False,
        postgresql_ops={"name_en_lower": "text_pattern_ops"},
    )
    op.create_index(
        "ix_cities_name_ru_prefix",
        "cities",
        [sa.literal_column("lower(name_ru)").label("name_ru_lower")],
        unique=False,
        postgresql_ops={"name_ru_lower": "text_pattern_ops"},
    )
    op.create_table(
        "daily_combo",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("card_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("day"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("props", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_created_at"), "events", ["created_at"], unique=False)
    op.create_index(op.f("ix_events_name"), "events", ["name"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("item_id", sa.String(length=32), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("telegram_payment_charge_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("is_subscription", sa.Boolean(), nullable=False),
        sa.Column("subscription_expiration", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_payment_charge_id"),
    )
    op.create_index(op.f("ix_payments_created_at"), "payments", ["created_at"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "referrals",
        sa.Column("invitee_id", sa.BigInteger(), nullable=False),
        sa.Column("inviter_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("l3_rewarded", sa.Boolean(), nullable=False),
        sa.Column("passive_snapshot", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("invitee_id"),
    )
    op.create_index(op.f("ix_referrals_inviter_id"), "referrals", ["inviter_id"], unique=False)
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title_ru", sa.String(length=200), nullable=False),
        sa.Column("title_en", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("tg_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("reward", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("max_completions", sa.Integer(), nullable=True),
        sa.Column("completions", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sponsor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("stars_paid", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_table(
        "user_badges",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("badge_id", sa.String(length=32), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=True),
        sa.Column(
            "awarded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "badge_id", "season_id"),
    )
    op.create_index(op.f("ix_user_badges_user_id"), "user_badges", ["user_id"], unique=False)
    op.create_table(
        "clans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("tg_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("invite_link", sa.Text(), nullable=True),
        sa.Column("photo_path", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("owner_user_id", sa.BigInteger(), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("members_count", sa.Integer(), nullable=False),
        sa.Column("subscribers_only", sa.Boolean(), nullable=False),
        sa.Column("season_points", sa.BigInteger(), nullable=False),
        sa.Column("promoted_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("banned", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_chat_id"),
    )
    op.create_index("ix_clans_season_points", "clans", ["season_points"], unique=False)
    op.create_index(
        "uq_clans_militia_city",
        "clans",
        ["city_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'militia'"),
    )
    op.create_table(
        "sectors",
        sa.Column("h3", sa.String(length=16), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("value", sa.SmallInteger(), nullable=False),
        sa.Column("owner_clan_id", sa.Integer(), nullable=True),
        sa.Column("defense", sa.BigInteger(), nullable=False),
        sa.Column("defense_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shield_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_actor_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_clan_id"],
            ["clans.id"],
        ),
        sa.PrimaryKeyConstraint("h3"),
    )
    op.create_index(op.f("ix_sectors_city_id"), "sectors", ["city_id"], unique=False)
    op.create_index("ix_sectors_lat_lng", "sectors", ["lat", "lng"], unique=False)
    op.create_index(op.f("ix_sectors_owner_clan_id"), "sectors", ["owner_clan_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=True),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column("photo_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("referrer_id", sa.BigInteger(), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("clan_id", sa.Integer(), nullable=True),
        sa.Column("clan_joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("coins", sa.BigInteger(), nullable=False),
        sa.Column("total_earned", sa.BigInteger(), nullable=False),
        sa.Column("passive_earned_total", sa.BigInteger(), nullable=False),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("energy_max", sa.Integer(), nullable=False),
        sa.Column(
            "energy_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("multitap_level", sa.SmallInteger(), nullable=False),
        sa.Column("income_per_hour", sa.BigInteger(), nullable=False),
        sa.Column("attack_bonus_bp", sa.Integer(), nullable=False),
        sa.Column("defense_bonus_bp", sa.Integer(), nullable=False),
        sa.Column(
            "last_passive_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_tap_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_action_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("daily_streak", sa.SmallInteger(), nullable=False),
        sa.Column("daily_last_date", sa.Date(), nullable=True),
        sa.Column("vip_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("offline_cap_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ref_claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("season_score", sa.BigInteger(), nullable=False),
        sa.Column("notify_enabled", sa.Boolean(), nullable=False),
        sa.Column("banned", sa.Boolean(), nullable=False),
        sa.Column("suspicion", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clan_id"],
            ["clans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_city_id"), "users", ["city_id"], unique=False)
    op.create_index(op.f("ix_users_clan_id"), "users", ["clan_id"], unique=False)
    op.create_index(op.f("ix_users_country_code"), "users", ["country_code"], unique=False)
    op.create_index(
        "ix_users_country_score", "users", ["country_code", "season_score"], unique=False
    )
    op.create_index(op.f("ix_users_referrer_id"), "users", ["referrer_id"], unique=False)
    op.create_index("ix_users_season_score", "users", ["season_score"], unique=False)
    op.create_table(
        "user_boosts",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("boost_id", sa.String(length=32), nullable=False),
        sa.Column("until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uses_today", sa.Integer(), nullable=False),
        sa.Column("uses_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "boost_id"),
    )
    op.create_table(
        "user_combo",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("found", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("claimed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "day"),
    )
    op.create_table(
        "user_tasks",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "task_id"),
    )
    op.create_table(
        "user_upgrades",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("card_id", sa.String(length=32), nullable=False),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "card_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_upgrades")
    op.drop_table("user_tasks")
    op.drop_table("user_combo")
    op.drop_table("user_boosts")
    op.drop_index("ix_users_season_score", table_name="users")
    op.drop_index(op.f("ix_users_referrer_id"), table_name="users")
    op.drop_index("ix_users_country_score", table_name="users")
    op.drop_index(op.f("ix_users_country_code"), table_name="users")
    op.drop_index(op.f("ix_users_clan_id"), table_name="users")
    op.drop_index(op.f("ix_users_city_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_sectors_owner_clan_id"), table_name="sectors")
    op.drop_index("ix_sectors_lat_lng", table_name="sectors")
    op.drop_index(op.f("ix_sectors_city_id"), table_name="sectors")
    op.drop_table("sectors")
    op.drop_index(
        "uq_clans_militia_city", table_name="clans", postgresql_where=sa.text("kind = 'militia'")
    )
    op.drop_index("ix_clans_season_points", table_name="clans")
    op.drop_table("clans")
    op.drop_index(op.f("ix_user_badges_user_id"), table_name="user_badges")
    op.drop_table("user_badges")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("seasons")
    op.drop_index(op.f("ix_referrals_inviter_id"), table_name="referrals")
    op.drop_table("referrals")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_created_at"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_events_name"), table_name="events")
    op.drop_index(op.f("ix_events_created_at"), table_name="events")
    op.drop_table("events")
    op.drop_table("daily_combo")
    op.drop_index(
        "ix_cities_name_ru_prefix",
        table_name="cities",
        postgresql_ops={"name_ru_lower": "text_pattern_ops"},
    )
    op.drop_index(
        "ix_cities_name_en_prefix",
        table_name="cities",
        postgresql_ops={"name_en_lower": "text_pattern_ops"},
    )
    op.drop_index("ix_cities_lat_lng", table_name="cities")
    op.drop_index(op.f("ix_cities_country_code"), table_name="cities")
    op.drop_index(op.f("ix_cities_controller_clan_id"), table_name="cities")
    op.drop_table("cities")
    op.drop_index(op.f("ix_battle_log_user_id"), table_name="battle_log")
    op.drop_index("ix_battle_log_prev_owner", table_name="battle_log")
    op.drop_index(op.f("ix_battle_log_created_at"), table_name="battle_log")
    op.drop_table("battle_log")
    op.drop_index(op.f("ix_ad_views_user_id"), table_name="ad_views")
    op.drop_index(op.f("ix_ad_views_created_at"), table_name="ad_views")
    op.drop_table("ad_views")
    # ### end Alembic commands ###
