"""battle_log prev_actor_id

Revision ID: 3bb9ff5060a1
Revises: b20beb29a1a1
Create Date: 2026-09-27 02:36:03.494654

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3bb9ff5060a1"
down_revision: str | None = "b20beb29a1a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("battle_log", sa.Column("prev_actor_id", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("battle_log", "prev_actor_id")
    # ### end Alembic commands ###
